# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Oh noes, what have you done now?
email: maarten@vanderaart.org
description: > # this means to ignore newlines until "baseurl:"
  Experiments, so not everybody has to reinvent the wheel all the time.
  Just sometimes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maarten.vanderaart.org" # the base hostname & protocol for your site
twitter_username: mraart
github_username:  maartenvanderaart

# Build settings
markdown: kramdown
